/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './greet.module';
import * as import2 from '@angular/core/src/di/injector';
import * as import3 from './greet.service';
class GreetModuleInjector extends import0.NgModuleInjector<import1.GreetModule> {
  _GreetModule_0:import1.GreetModule;
  __GreetService_1:any;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _GreetService_1():any {
    if ((this.__GreetService_1 == null)) { (this.__GreetService_1 = import1.GreetComponentFactory()); }
    return this.__GreetService_1;
  }
  createInternal():import1.GreetModule {
    this._GreetModule_0 = new import1.GreetModule();
    return this._GreetModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.GreetModule)) { return this._GreetModule_0; }
    if ((token === import3.GreetService)) { return this._GreetService_1; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const GreetModuleNgFactory:import0.NgModuleFactory<import1.GreetModule> = new import0.NgModuleFactory(GreetModuleInjector,import1.GreetModule);